version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './:/var/www'

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - './:/var/www'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - php
