monolog:
    channels: ["integration"]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        integration:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%_integration.log"
            level: debug
            channels: ["integration"]
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
