services:
    _defaults:
        autowire: true
        autoconfigure: true
    Application\:
        resource: '../src/Application'
        exclude:
            - '../src/Application/Kernel.php'
    Core\:
        resource: '../src/Core'

    Core\Domain\Integration\CommandHandler\SaveIntegrationProductCommandHandler:
        arguments:
            $logger: '@monolog.logger.integration'

    Application\Service\IntegrationService:
        arguments:
            $logger: '@monolog.logger.integration'